language: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install codecov
script:
    - pytest --cov=./
after_success:
    - bash <(curl -s https://codecov.io/bash) -t 52056cf4-dbc4-40a2-bc76-63b7afd1ae93
